spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ENC(bdqsN6A7Bjtx3EFH5zTb46hS/u4n2rmyUcHUS9hBp8fKiB8ZPwGaTGdJjjbLrTCV8jcmYB9NCx05eEbDV8FuhXdhTZrUyUX9GOB4PEdzv6FHMECvyJCpibYgEl/PS2CJ48fIaFnbcXQ=)
    username: ENC(Z0AxqVGKRiSeyc1JhT/+Zg==)
    password: ENC(veluC6wSk7R6VPdJ6HdlDg==)
  jpa:
    hibernate:
      ddl-auto: update
      dialect: com.cuiwz.config.MysqlConfig
    show-sql: true

logging:
  level:
    root: info
    com.cuiwz: debug
  file: log/blog-dev.log

server:
  port: 80

jasypt:
  encryptor:
    password: EbfYkitulv73I2p0mXI50JMXoaxZTKJ7