spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(F1+YnlELc8JtuVXuRCsbyiedndlaHQiqNtaunInIGPvHQAXD/j5vSFU3ZMtTXgdOqPlS74cjaHu/udoHVTQgHp7iLXP/zSBTTNpAyrR7Pc1E1pKs7GzgpeuExp8pM80lJ4uUWdQgx4s=)
    username: ENC(yhv9gkW7Vh0WzY5GHHRxww==)
    password: ENC(ICQEKLzRHK3L8owIMtHijg==)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false # 启用缓存:建议生产开启
    check-template-location: true # 检查模版是否存在
    enabled: true # 是否启用
    encoding: UTF-8 # 模版编码
    excluded-view-names: # 应该从解析中排除的视图名称列表（用逗号分隔）
    mode: HTML5 # 模版模式
    prefix: classpath:/templates/ # 模版存放路径
    suffix: .html # 模版后缀

logging:
  level:
    root: info
    com.cuiwz: debug
  file: log/blog-dev.log

server:
  port: 80

jasypt:
  encryptor:
    password: EbfYkitulv73I2p0mXI50JMXoaxZTKJ7